-------------------------------------------------------------------------------
-- Filename   : plugins.lua                                                  --
-- Author     : Michael DeBusk (https://gitlab.com/mdebusk/)                 --
-- Created    : 2022-12-15                                                   --
-- Last edit  : 2025-06-09 01:28                                             --
-- Purpose    : Handles plugins in neovim                                    --
-- Reference  : https://youtu.be/w7i4amO_zaE                                 --
-- Depends    : neovim                                                       --
-- Known bugs : NKA                                                          --
-- TODO       : N/A                                                          --
-------------------------------------------------------------------------------

