" Vim configuration file for Michael DeBusk
" https://github.com/mdebusk
" Last edit: 2021-08-04 14:11


" ** 1. Important "{{{
set nocompatible         "Turn off vi-compatible mode
"}}}

" ** 2. Moving around, searching and patterns "{{{
set autochdir            "Automatically change working directory to that of open file
set ignorecase           "ignore case when using a search pattern
set incsearch            "show match for partly-typed search command
set path+=**             "Search down into subfolders
set smartcase            "override 'ignorecase' when pattern has upper case characters
"}}}

" ** 3. Tags "{{{
"}}}

" ** 4. Displaying text "{{{
set cmdheight=2          "Set the command window height to 2 lines
set fillchars+=fold:·    " Set fill character for folds
set lazyredraw           "Don’t update screen during macro and script execution
set list                 "Show whitespace characters
set listchars=tab:╠═,trail:░,nbsp:▃      "List of strings used for list mode
set nowrap               "Turn off word wrapping
set number               "Enable line numbering, taking up 6 spaces
set numberwidth=5        "Set line numbering to take up 5 spaces
set relativenumber       "Show line numbers relative to current line
set scrolloff=3          "Number of lines to show around the cursor
augroup numbertoggle     "Toggles relativenumber on and off based on mode
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
"}}}

" ** 5. Syntax highlighting and spelling "{{{
filetype indent plugin on "indent depends on filetype
set background=dark
set colorcolumn=+1        "Show the column where text would wrap
set cursorline            "Highlight current line
set hlsearch              "Highlight searches
syntax enable
"}}}

" ** 6. Multiple Windows "{{{
set hidden               "Allow easier switching between files
set laststatus=2         "Always display the status line
set splitbelow           "Always open a new horizontal split below the existing one
set splitright           "Always open a new vertical split below the existing one
set statusline=%F%m%r%h%w\ [Fmt=%{&ff}]\ [Type=%Y]\ [ASCII=\%04.4b]\ [Hex=\%04.4B]\ [Line=%04l,\ Col=%03v]\ [%p%%]\ [Lines=%L]
"}}}

" ** 7. Multiple tab pages "{{{
"}}}

" ** 8. Terminal "{{{
set title                "show title in console title bar
set ttyfast              "smoother changes
"}}}

" ** 9. Using the mouse "{{{
"}}}

" ** 10. GUI "{{{
if has("gui_running")
    let g:solarized_menu=0            "Activate menu for Solarized color scheme
    set guifont=OpenDyslexicMono\ 9   "Set the font and size
    set guioptions-=L                 "Remove left scrollbar
    set guioptions-=T                 "Remove toolbar
    set guioptions-=m                 "Remove menu bar
    set guioptions-=r                 "Remove right scrollbar
    "set lines=43 columns=120         "Not useful with a tiling window manager
endif
"}}}

" ** 11. Printing "{{{
set printdevice=pdf     "Use PDF printer
set printoptions=paper:letter,syntax:y,wrap:y,duplex:long
"}}}

" ** 12. Messages and info "{{{
set confirm              "ask if you wish to save changed files
set ruler                "show the cursor position all the time
set showcmd              "Show partial commands in the status line
set visualbell           "Use visual bell instead of beeping when doing something wrong
"}}}

" ** 13. Selecting text "{{{
"}}}

" ** 14. Editing text "{{{
set complete+=kspell
set completeopt=menuone,longest
set nojoinspaces
set omnifunc=syntaxcomplete#Complete
set undodir=~/.vim/undodir
set undofile
"set textwidth=80        "Set text width, where text would wrap if it did
"set wrapmargin=80
"}}}

" ** 15. Tabs and indenting "{{{
set autoindent           "Automatically set the indent of a new line
set expandtab            "turn tabs into whitespace
set shiftround           " use multiple of shiftwidth when indenting with '<' and '>'
set shiftwidth=4         "Indent width for autoindent
set smartindent          "Turn on smart indent
set softtabstop=4        "Number of spaces a tab counts when editing
set tabstop=4            "set tab character to 8 characters
"}}}

" ** 16. Folding "{{{
set foldlevel=99
set foldmethod=marker
"}}}

" ** 17. Diff mode "{{{
"}}}

" ** 18. Mapping "{{{
"Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

" In case you open a file without sudo permissions
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

"Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy,
"which is the default
map Y y$

"Map <C-L> (redraw screen) to also turn off search highlighting until the
"next search
nnoremap <C-L> :nohl<CR><C-L>

" Disable arrow movement, resize splits instead.
nnoremap <Up> :resize +2<CR>
nnoremap <Down> :resize -2<CR>
nnoremap <Left> :vertical resize +2<CR>
nnoremap <Right> :vertical resize -2<CR>

" Keep the cursor centered during search and join
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap J mzJ`z

" Undo break points
inoremap , ,<c-g>u
inoremap . .<c-g>u
inoremap ! !<c-g>u
inoremap ? ?<c-g>u

" Don't leave visual mode when (un)indenting
vnoremap < <gv
vnoremap > >gv

" Autoclose mappings "{{{2
" From https://medium.com/vim-drops/custom-autoclose-mappings-1ff90f45c6f5
" autoclose and position cursor to write text inside
" inoremap ' ''<left>
" inoremap ` ``<left>
" inoremap " "<left>
" inoremap ( ()<left>
" inoremap [ []<left>
" inoremap { {}<left>
""autoclose with ; and position cursor to write text inside
" inoremap '; '';<left><left>
" inoremap `; ``;<left><left>
" inoremap "; "";<left><left>
" inoremap (; ();<left><left>
" inoremap [; [];<left><left>
" inoremap {; {};<left><left>
""autoclose with , and position cursor to write text inside
" inoremap ', '',<left><left>
" inoremap `, ``,<left><left>
" inoremap ", "",<left><left>
" inoremap (, (),<left><left>
" inoremap [, [],<left><left>
" inoremap {, {},<left><left>
""autoclose and position cursor after
" inoremap '<tab> ''
" inoremap `<tab> ``
" inoremap "<tab> ""
" inoremap (<tab> ()
" inoremap [<tab> []
" inoremap {<tab> {}
""autoclose with ; and position cursor after
" inoremap ';<tab> '';
" inoremap `;<tab> ``;
" inoremap ";<tab> "";
" inoremap (;<tab> ();
" inoremap [;<tab> [];
" inoremap {;<tab> {};
""autoclose with , and position cursor after
" inoremap ',<tab> '',
" inoremap `,<tab> ``,
" inoremap ",<tab> "",
" inoremap (,<tab> (),
" inoremap [,<tab> [],
" inoremap {,<tab> {},
""autoclose 2 lines below and position cursor in the middle
" inoremap '<CR> '<CR>'<ESC>O
" inoremap `<CR> `<CR>`<ESC>O
" inoremap "<CR> "<CR>"<ESC>O
" inoremap (<CR> (<CR>)<ESC>O
" inoremap [<CR> [<CR>]<ESC>O
" inoremap {<CR> {<CR>}<ESC>O
""autoclose 2 lines below adding ; and position cursor in the middle
" inoremap ';<CR> '<CR>';<ESC>O
" inoremap `;<CR> `<CR>`;<ESC>O
" inoremap ";<CR> "<CR>";<ESC>O
" inoremap (;<CR> (<CR>);<ESC>O
" inoremap [;<CR> [<CR>];<ESC>O
" inoremap {;<CR> {<CR>};<ESC>O
""autoclose 2 lines below adding , and position cursor in the middle
" inoremap ',<CR> '<CR>',<ESC>O
" inoremap `,<CR> `<CR>`,<ESC>O
" inoremap ",<CR> "<CR>",<ESC>O
" inoremap (,<CR> (<CR>),<ESC>O
" inoremap [,<CR> [<CR>],<ESC>O
" inoremap {,<CR> {<CR>},<ESC>O
"}}}
"}}}

" ** 19. Reading and writing files "{{{
"Turn off modeline support.
"http://blogs.techrepublic.com.com/security/?p=4476
set autowrite            "Writes file when switching to another buffer
set backup               "keep a backup file
set modelines=0          "Do not check for existing modelines
set nomodeline           "Disable modeline support
"}}}

" ** 20. The swap file "{{{
"}}}

" ** 21. Command line editing "{{{
set wildmenu             "turn on command line completion wild style
"}}}

" ** 22. Running external commands "{{{
"}}}

" ** 23. Running make and jumping to errors "{{{
"}}}

" ** 24. Language-specific "{{{
"}}}

" ** 25. Multi-byte characters "{{{
set encoding=utf-8       "Use an encoding that supports unicode.
"}}}

" ** 26. Various "{{{
set bufhidden=hide       "Hide buffer when not in window
set signcolumn=yes
set viminfo='20,\"50     "Read/write a .viminfo file
"}}}

" ** Color scheme "{{{
set t_Co=256
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized
"}}}

" ** Customized file types "{{{
augroup views            "Back up and restore views on buffer open
    autocmd!
    au BufWinLeave ?* mkview
    au BufWinEnter ?* silent loadview
augroup END

augroup filetype_LaTeX
    autocmd!
    " copy document template into empty new buffer
    au BufNewFile *.tex
                \ 0r /home/michael/Templates/latex_document.tex

    au BufNewFIle,BufRead *.tex
                \ :iab latex \LaTeX\
augroup END

augroup filetype_bash
    autocmd!
    " copy script template into empty new buffer
    au BufNewFile *.sh
                \ 0r /home/michael/Templates/shell_script.sh
augroup END

augroup filetype_python
    " Delete all trailing whitespace before saving
    au BufWritePre *.py :%s/\s\+$//e

    au BufNewFile,BufRead *.py
                \ set tabstop=4 |
                \ set softtabstop=4 |
                \ set shiftwidth=4 |
                \ set textwidth=79 |
                \ set expandtab |
                \ set autoindent |
                \ set smartindent |
                \ set colorcolumn=80 |
                \ set fileformat=unix
augroup END

augroup web_development
    au BufNewFile,BufRead *.js, *.html, *.css, *.php
                \ set tabstop=2 |
                \ set softtabstop=2 |
                \ set shiftwidth=2

    " copy HTML document template into empty new buffer
    au bufnewfile *.html
                \ 0r /home/michael/Templates/html_document.html
augroup END

"}}}

" ** Abbreviations "{{{
" Insert date (and maybe time)
:iab <expr> dts strftime("%F %R")    "Date/time stamp
:iab <expr> dtg strftime("%e %b %Y") "Date style used in genealogy

" for QIF files
:iab ckng MAutopay<CR>LAssets:Current Assets:Capital One 360:Checking

" Insert a ruler
:iab RuL ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0
"}}}

" ** Plugins "{{{
"" Make netrw look like NERDtree
"" https://shapeshed.com/vim-netrw/
"let g:netrw_banner = 0
"let g:netrw_liststyle = 3
"let g:netrw_browse_split = 4
"let g:netrw_altv = 1
"let g:netrw_winsize = 25
"augroup ProjectDrawer
  "autocmd!
  "autocmd VimEnter * :Vexplore
"augroup END
"}}}
