###############################################################################
# Filename   : bash_aliases                                                   #
# Author     : Michael DeBusk (https://gitlab.com/mdebusk/)                   #
# Created    : 2022-07-04 13:16                                               #
# Last edit  : 2024-03-08 00:43                                               #
# Purpose    : aliases for interactive bash shell, sourced from ~/.bashrc     #
# Depends    : bash, other programs as listed                                 #
# Known bugs : NKA                                                            #
# TODO       : N/A                                                            #
###############################################################################

# ** License {{{
###############################################################################
# This is free and unencumbered software released into the public domain.     #
#                                                                             #
# Anyone is free to copy, modify, publish, use, compile, sell, or             #
# distribute this software, either in source code form or as a compiled       #
# binary, for any purpose, commercial or non-commercial, and by any means.    #
#                                                                             #
# In jurisdictions that recognize copyright laws, the author or authors of    #
# this software dedicate any and all copyright interest in the software to    #
# the public domain. We make this dedication for the benefit of the public    #
# at large and to the detriment of our heirs and successors. We intend        #
# this dedication to be an overt act of relinquishment in perpetuity of       #
# all present and future rights to this software under copyright law.         #
#                                                                             #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,             #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF          #
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.      #
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER     #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         #
# DEALINGS IN THE SOFTWARE.                                                   #
#                                                                             #
# For more information, please refer to <http://unlicense.org/>               #
###############################################################################
# End license }}}


# ** Sane defaults for potentially-destructive commands {{{
alias chgrp='chgrp --preserve-root'
alias chmod='chmod --preserve-root'
alias chown='chown --preserve-root'
alias cp='cp -i'
alias ln='ln -i'
alias mv='mv -i'
alias rm='rm -i'
# End sane defaults }}}


# ** Other useful defaults {{{
alias df='df -Tha --total'
alias free='free -hltw'
alias ip='ip -color=auto'
alias grep='grep --color=auto'
alias ls='ls -hlpv --color=auto --group-directories-first --time-style=long-iso'
alias nvlc='nvlc --browse-dir ~/Music' # NCurses version of VLC
alias ping='ping -c 3'
alias wget='wget -c'
alias xclip='xclip -sel clip'
# End other useful defaults }}}


# ** Help programs use the XDG Base Directory standard {{{
alias abook='abook --config "$XDG_CONFIG_HOME"/abook/abookrc --datafile "$XDG_DATA_HOME"/abook/addressbook'
alias dosbox='dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox-0.74-3.conf'
## alias mysql-workbench="mysql_workbench.sh"
alias remind='remind -@2,0,1 "$XDG_CONFIG_HOME"/remind/reminders.rem'
alias slrn='slrn -i "$XDG_CONFIG_HOME"/slrn/slrnrc -f "$XDG_CONFIG_HOME"/slrn/jnewsrc-september'
alias sqlite3='sqlite3 -init "$XDG_CONFIG_HOME"/sqlite3/sqliterc'
alias t='python "$HOME"/Source/t/t.py --task-dir "$XDG_DATA_HOME"/tasks --list tasks'
alias tkremind='tkremind "$XDG_CONFIG_HOME"/remind/reminders.rem'
# End XDG Base Directory Standard }}}


# ** New "commands" {{{

# alias for bare git repo use (dotfile repo)
# https://www.atlassian.com/git/tutorials/dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# Diary
alias dz='pushd ~/Documents && echo -e "\n## `date -Is` {{{\n\n}}}" >> diary.md && vim "+ normal Gk" +startinsert diary.md && popd'

# What are my external and internal IP addresses?
alias ips='echo "External IP: $(curl -s https://ifconfig.co)" ; echo "Internal IP: $(hostname -I)"'

# Start Joplin terminal version
alias joplincli='~/bin/Joplin/bin/joplin'

# Show hidden files in directory listing
alias la='ls -Ahlpv --color=auto --group-directories-first --time-style=long-iso'

# Use wget to mirror a Web site
alias mirror='wget --mirror --convert-links --html-extension --wait=2 -o log'

# Emulates MS-DOS "pause" command
alias pause='echo -n "Press any key to continue... " && read -n 1 -s && echo'

# Password generator
alias pwgen='echo -e "\n$(tr -dc A-Za-z0-9_ < /dev/urandom | head -c 32 | xargs)\n"'

# Use vim as a pager with syntax highlighting
alias vless='/usr/local/share/vim/vim91/macros/less.sh'

# Find zombie processes
alias zombie='ps axo stat,ppid,pid,comm | grep -w defunct'
# End new "commands" }}}
