###############################################################################
# Filename   : alacritty.toml                                                 #
# Author     : Michael DeBusk (https://gitlab.com/mdebusk/)                   #
# Created    : 2023-07-24 01:30                                               #
# Last edit  : 2024-12-07 19:04                                               #
# Purpose    : Configuration file for alacritty                               #
# Reference  : https://alacritty.org/config-alacritty.html                    #
# Depends    : alacritty version 14.0 or above                                #
# Known bugs : NKA                                                            #
# TODO       : N/A                                                            #
###############################################################################

# ** License {{{
###############################################################################
# This is free and unencumbered software released into the public domain.     #
#                                                                             #
# Anyone is free to copy, modify, publish, use, compile, sell, or             #
# distribute this software, either in source code form or as a compiled       #
# binary, for any purpose, commercial or non-commercial, and by any means.    #
#                                                                             #
# In jurisdictions that recognize copyright laws, the author or authors of    #
# this software dedicate any and all copyright interest in the software to    #
# the public domain. We make this dedication for the benefit of the public    #
# at large and to the detriment of our heirs and successors. We intend        #
# this dedication to be an overt act of relinquishment in perpetuity of       #
# all present and future rights to this software under copyright law.         #
#                                                                             #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,             #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF          #
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.      #
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER     #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         #
# DEALINGS IN THE SOFTWARE.                                                   #
#                                                                             #
# For more information, please refer to <http://unlicense.org/>               #
###############################################################################
# End license }}}

[general] # {{{
import = ["~/.config/alacritty/solarized_dark.toml"]
live_config_reload = true
working_directory = "None"

# End general }}}

[env] # {{{
WINIT_X11_SCALE_FACTOR = "1.0"
# End env }}}

[window] # {{{
## blur = true # needs Wayland
class = { instance = "Alacritty", general = "Alacritty" }
decorations = "full" # | "none"
decorations_theme_variant = "Dark" # "Light" "None"
dimensions = { columns = 0, lines = 0 }
dynamic_padding = false
dynamic_title = true
opacity = 0.8
padding = { x = 5, y = 5 }
position = "None" # | { x = <integer>, y = <integer> }
## startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
resize_increments = false
title = "Alacritty"
# End window }}}

[scrolling] # {{{
history = 10000
multiplier = 3
# End scrolling }}}

[font] # {{{
builtin_box_drawing = true
normal = { family = "Azeret Mono", style = "Regular" }
bold = { family = "Azeret Mono", style = "Bold" }
bold_italic = { family = "Azeret Mono", style = "Bold Italic" }
italic = { family = "Azeret Mono", style = "Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
size = 16
# End font }}}

[bell] # {{{
###############################################################################
# Available animation types are "Ease", "EaseOut", "EaseOutSine",             #
#                               "EaseOutQuad", "EaseOutCubic",                #
#                               "EaseOutQuart", "EaseOutQuint",               #
#                               "EaseOutExpo", "EaseOutCirc",                 #
#                                and "Linear"                                 #
###############################################################################
animation = "EaseOutExpo"
command = "None"
color = "#fdf6e3"
duration = 20
# End ball }}}

[selection] # {{{
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false
# End selection }}}

[cursor] # {{{
## style = { "Block", "Off" }
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15
# End cursor }}}

[terminal] # {{{
osc52 = "OnlyCopy"
shell="/usr/bin/bash"
# End terminal }}}

[mouse] # {{{
hide_when_typing = true
# End mouse }}}

[hints] # {{{
# See the manual
# End hints }}}

[keyboard] # {{{
# This should be an external file for organization
# See the manual
# End keyboard }}}

[debug] # {{{
# See the manual
# End debug }}}
