######################################################################
# Filename   : alacritty.toml                                        #
# Author     : Michael DeBusk (https://gitlab.com/mdebusk/)          #
# Created    : 2023-07-24 01:30                                      #
# Last edit  : 2023-07-24 01:42                                      #
# Purpose    : Configuration file for alacritty                      #
# Depends    : alacritty                                             #
# Known bugs : NKA                                                   #
# TODO       : N/A                                                   #
######################################################################

# size = 9
# window_opacity = 0.8

[bell]
animation = "EaseOutExpo"
color = "#fdf6e3"
duration = 20

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font.bold]
family = "Azeret Mono"
style = "Bold"

[font.bold_italic]
family = "Azeret Mono"
style = "Bold Italic"

[font.italic]
family = "Azeret Mono"
style = "Italic"

[font.normal]
family = "Azeret Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_title = true
title = "Alacritty"
# "window.decorations_theme_variant" = "dark"

[window.padding]
x = 5
y = 5
