######################################################################
# Filename   : alacritty.toml                                        #
# Author     : Michael DeBusk (https://gitlab.com/mdebusk/)          #
# Created    : 2023-07-24 01:30                                      #
# Last edit  : 2023-12-31 13:14                                      #
# Purpose    : Configuration file for alacritty                      #
# Depends    : alacritty                                             #
# Known bugs : NKA                                                   #
# TODO       : N/A                                                   #
######################################################################

import = [
    "~/.config/alacritty/solarized_dark.toml"
]

[bell]
animation = "EaseOutExpo"
color = "#fdf6e3"
duration = 20

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font.bold]
family = "Azeret Mono"
style = "Bold"

[font.bold_italic]
family = "Azeret Mono"
style = "Bold Italic"

[font.italic]
family = "Azeret Mono"
style = "Italic"

[font.normal]
family = "Azeret Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[shell]
program="/usr/bin/bash"

[window]
## blur = true # needs Wayland
decorations = "none"
dynamic_title = true
opacity = 0.8
title = "Alacritty"
## "window.decorations_theme_variant" = "dark"

[window.padding]
x = 5
y = 5
